### ISSUE TITLE
Feature Request: a 'vim tutor' style learning resource

### ISSUE THREAD

**Issue by mimuki** [cursorless-dev/cursorless#1552] opened 2023-06-28 10:49 UTC
something that walks you through the basics of using cursorless with hands on examples, essentially. I've been struggling to wrap my head around it just reading the documentation, and I'm sure I'm not the only one who learns by doing :)

**Comment by pokey** [comment] 2023-06-28 10:54
Duplicate of https://github.com/cursorless-dev/cursorless/issues/934

**Closed by pokey** 2023-06-28 10:54 UTC

**Comment by pokey** [comment] 2023-06-28 17:30
Sorry if my response was a bit abrupt 😅. Feel free to comment on that other issue if you have ideas for how to make it even better 😊
