### ISSUE TITLE
spurious "undefined" text inserted

### ISSUE THREAD

**Issue by josharian** [cursorless-dev/cursorless#1517] opened 2023-06-07 13:58 UTC
I haven't figured out the reproduction conditions, but I have a screen recording of it occurring locally.

Note the text "undefined" near the beginning of the second line at the end of the video.

Version 3a66f6754bb99536f2dfdc89f664785de23c428a

https://github.com/cursorless-dev/cursorless/assets/67496/db8365d9-b319-4bed-ba0b-4ceb551179ea

**Comment by pokey** [comment] 2023-06-09 12:42
Huh super odd.  I couldn't reproduce it locally using your text.  Is it reproducible when doing that exact action on that exact text for you?  It looks like what's happening is that the target that's constructed by `"three tokens"` has an `undefined` insertion delimiter.  It should be `" "`, so that it inserts a space between the tokens and the next token, and should really never be `undefined`

**Comment by josharian** [comment] 2023-06-10 02:04
It reproduced 100% for me at the time. I’m in the Canadian Rockies and about to go offline again, so I can’t check. But I will follow up in July. In case it might matter, this was in “draft editor” mode, and I recently have messed around with the string formatter in knausj (but it was always working).

**Comment by AndreasArvidsson** [comment] 2023-07-03 07:09
I've tried to reproduce the problem and I can't. The first obvious thing I see is that you should probably use `token` and not `word` in this case. `hello_world` is one token, but two words and can trip you up in the future if you get used to using words to refer to tokens.

**Comment by josharian** [comment] 2023-07-03 16:10
Thanks for the reminder. I just checked and I can still reproduce this one hundred percent.

Using `The big dwarf only jumps.` as the text (thanks to Wikipedia for the [heterogram](https://en.wikipedia.org/wiki/Heterogram_(literature))):

Reproduces:

`move two words odd before bat`
`move two words bat after odd`
`move two words trap after odd`

Do not reproduce:

`move one word odd before bat`
`take two words drum`
`move two tokens odd before bat`
`move two chars odd before bat`

It looks to be specific to moving multiple words.

What should I do next to help debug? Are there any tips/docs to getting set up to hack on the extension? Though my TypeScript is weak, I'm a reasonably good developer, and happy to help dig in.

> hello_world is one token, but two words and can trip you up in the future if you get used to using words to refer to tokens.

Noted. I already use "tokens" when coding; apparently my brain views English text as different. :P

**Comment by josharian** [comment] 2023-07-03 16:20
To confirm, I also stashed all of my knausj changes, and its story produces. The only alteration to my cursorless settings that I have made is to define one user color (white, because I only use dark mode).

**Comment by AndreasArvidsson** [comment] 2023-07-03 16:22
I just tried with your example above and I don't get any problems/undefined. Are you on the latest version of vscode and Cursorless?

**Comment by josharian** [comment] 2023-07-03 16:44
VSCode:

```
Version: 1.79.2 (Universal)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:58:52.392Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

Cursorless extension: `0.26.718`
cursorless-talon: `3a66f6754bb99536f2dfdc89f664785de23c428a`

**Comment by josharian** [comment] 2023-07-03 16:52
Okay. I'll get set up to make recordings. May not happen until later this week.

**Comment by AndreasArvidsson** [comment] 2023-07-03 16:53
No stress. I will have a look at it as soon as I have some more data.

**Comment by josharian** [comment] 2023-07-03 20:21
In response to an unrelated problem I had with drafts, I deleted axkit. On a hunch, I checked again whether this still reproduces. It does not.

So whatever the problem was, it was a bad interaction with axkit. Given that I have had two bad experiences with axkit today, I'm going to abandon it. Up to you whether you would like to leave this open, or close it as wontfix.

**Comment by AndreasArvidsson** [comment] 2023-07-04 09:10
Good that you found the source of the problem. I think we will close it for now and if you have any further problem we can always open it again.

**Closed by AndreasArvidsson** 2023-07-04 09:10 UTC
Labels: can't reproduce
