### ISSUE TITLE
Corsorless spoken forms for scopes do not work if the user has no settings.json file for vscode.

### ISSUE THREAD

**Issue by BrendanNolan** [cursorless-dev/cursorless#2694] opened 2024-12-02 08:49 UTC
When I installed vscode and Cursorless on my M2 macbook, spoken forms for scopes (like "funk" or "line") didn't work. From reading the talon log, I could see that this was due to the vscode `settings.json` file not being found. When I created a `settings.json` file (at `$HOME/Library/Application\ Support/Code/User/settings.json`) containing just an empty JSON object `{}` , everything worked fine.

For new users (particularly people who, like me, have switched from other editors to vscode in order to use Cursorless, and who thus have fresh installations of vscode with no `settings.json` file), it would be good to treat the settings as empty if no `setings.json` file is found.

**Comment by AndreasArvidsson** [comment] 2024-12-02 09:07
Did you try to restart Talon after you clone cursorless-talon?

https://www.cursorless.org/docs/user/installation/#installing-the-talon-side

**Comment by auscompgeek** [comment] 2024-12-02 09:48
See also #543

**Comment by BrendanNolan** [comment] 2024-12-02 09:54
> Did you restart Talon after you cloned cursorless-talon?
> 
> https://www.cursorless.org/docs/user/installation/#installing-the-talon-side

I did but it didn't work until I created the settings.json file.

**Comment by pokey** [comment] 2024-12-05 14:31
yeah this is a duplicate of #543 so I'm going to close to keep the discussion in one place. Thanks for filing, though

**Closed by pokey** 2024-12-05 14:31 UTC
