### ISSUE TITLE
can't open cheatsheet

### ISSUE THREAD

**Issue by asg0451** [cursorless-dev/cursorless#969] opened 2022-09-19 16:49 UTC
i just installed cursorless in vscode, and everything seems to be working except "cursorless cheatsheet". it does nothing. "cursorless help" opens docs in safari.

vscode is focused

**Comment by asg0451** [comment] 2022-09-19 19:03
also nothing

"cursorless help" opens https://www.cursorless.org/docs/ in chrome

**Comment by pokey** [comment] 2022-09-19 20:20
Huh. Do you see anything in the talon log? You can see it by saying "talon open log"

**Comment by asg0451** [comment] 2022-09-19 20:39
ahh

```
Exception: A system error occurred (ENOENT: no such file or directory, open '/var/folders/h0/49j4d8jd4dv48k65mx5gy0wm0000gp/T/tmpldt26qb8/cheatsheet.html')
2022-09-19 15:03:38 ERROR    13:                                talon/scripting/talon_script.py:589| 
   12:                                talon/scripting/talon_script.py:297| 
   11:                                talon/scripting/talon_script.py:556| 
   10:                                     talon/scripting/actions.py:85 | 
    9:                                       talon/scripting/types.py:411| 
    8:       user/cursorless-talon/src/cheatsheet_html/cheat_sheet.py:42 | actions.user.vscode_with_plugin_and_wa..
    7:                                     talon/scripting/actions.py:85 | 
    6:                                       talon/scripting/types.py:411| 
    5:         user/knausj_talon/apps/vscode/command_client/vscode.py:79 | actions.user.run_rpc_command_and_wait(..
    4:                                     talon/scripting/actions.py:85 | 
    3:                                       talon/scripting/types.py:411| 
    2: user/knausj_talon/apps/vscode/command_client/command_client.py:314| run_command(
    1: user/knausj_talon/apps/vscode/command_client/command_client.py:199| raise Exception(decoded_contents["error"])
Exception: A system error occurred (ENOENT: no such file or directory, open '/var/folders/h0/49j4d8jd4dv48k65mx5gy0wm0000gp/T/tmpldt26qb8/cheatsheet.html')

```

btw this is a remote workspace over ssh. think that matters?

**Comment by pokey** [comment] 2022-09-20 06:26
Ah yeah you're hitting https://github.com/cursorless-dev/cursorless/issues/911

**Comment by asg0451** [comment] 2022-09-20 14:08
:( is there a recommended workaround atm? i have no way to see even the basic (uncustomized) commands and no way to learn to use this software

**Comment by asg0451** [comment] 2022-09-20 14:25
....like if you could just send me a screenshot of the default cheetsheet that would be enough for now

**Comment by pokey** [comment] 2022-09-20 14:26
Easiest workaround would be to just open a local workspace, no?

**Comment by pokey** [comment] 2022-09-20 14:31
> i have no way to see even the basic (uncustomized) commands and no way to learn to use this software

While the cheatsheet is undoubtedly a useful reference, I would not recommend using it to learn Cursorless, as it is quite terse, and makes no effort to explain what any actions or scope types actually do.  It is much better for use as a reference once you're already familiar with the concepts and what the actions do.

The [documentation](https://www.cursorless.org/docs), [videos](https://www.youtube.com/watch?v=5mAzHGM2M0k&list=PLXv2sppxeoQZz49evjy4T0QJRIgc_JPqs), and [katas](https://github.com/Will-Sommers/cursorless-katas) should be a better way to learn at the beginning

All that being said, I believe my workaround above should work: just open a local workspace and say "cursorless cheatsheet".  The url it takes you to is just a local file so you should be able to bookmark that URL and close the local workspace

**Comment by asg0451** [comment] 2022-09-20 14:33
ah yeah that works, thanks!

yeah i did go through the videos and the docs, but without a full list of actions i had no idea how to actually do anything

**Comment by pokey** [comment] 2022-09-20 14:34
Hmm.  I still feel there must be a gap in our docs if you need to use the cheatsheet to figure out how to actually do anything.

**Comment by asg0451** [comment] 2022-09-20 14:35
that's fair yeah. dont think it's an urgent issue as the cheatsheet is very usable.... as long as you can access it

**Comment by asg0451** [comment] 2022-09-20 14:36
maybe a quick update to the docs about accessing the cheatsheet in remote workspaces?

**Comment by auscompgeek** [comment] 2022-09-21 08:36
The plan is to just fix it so it works regardless.

Just so GitHub does its thing:

Duplicate of #911

**Comment by auscompgeek** [comment] 2022-09-21 08:37
huh, maybe the thing doesn't work on closed issues. 🤷

**Comment by pokey** [comment] 2022-09-21 10:46
> huh, maybe the thing doesn't work on closed issues. 🤷

what is "the thing"?

**Comment by pokey** [comment] 2022-09-21 10:47
@asg0451 ok the cheatsheet should now work with remote workspaces as of Cursorless version 0.26.439 and parse-tree extension version 0.23.0.  If you could update your extensions both locally and in the remote workspace and try the cheatsheet again, that would be great!  I don't have any remote workspaces to test on

**Comment by auscompgeek** [comment] 2022-09-21 10:49
> what is "the thing"?

If you comment on an issue with `Duplicate of #` GitHub will actually mark the issue as a duplicate

**Comment by pokey** [comment] 2022-09-21 10:50
Duplicate of #911

**Comment by pokey** [comment] 2022-09-21 10:50
Hmm, yeah looks like that worked.  Not sure what that accomplishes practically speaking, but Github does seem to have detected some magic

**Closed by pokey** 2022-09-21 10:50 UTC
Labels: duplicate

**Comment by asg0451** [comment] 2022-09-21 15:59
it works 👍 👍  thanks guys

**Comment by pokey** [comment] 2022-09-21 18:22
...and just to confirm, Cursorless itself still works, right? 😅.  Worth testing with some scope types in a supported language, eg "take funk", as the change relied on the parse tree extension as well

**Comment by asg0451** [comment] 2022-09-21 18:24
yep still works, thanks!
