### ISSUE TITLE
"pre every item" treats line comments as an item

### ISSUE THREAD

**Issue by Will-Sommers** [cursorless-dev/cursorless#660] opened 2022-04-29 21:12 UTC
**Expected Behavior:**
I think that there is a question here as to the correct behavior. Should we take the comment too? In cases where we are deleting, that might make sense. However, in copy/paste scenarios it might not make sense.

Possible "correct behavior"
- Take everything
- Take only the item
- Provider a modifier to allow for taking just the item, or everything.
- Look at updating `"give"` to work within sub-selections and avoid using inference

**Bug:**
Currently comments and items within a list are each given a selection.

I observed this in javascript(see below) but also tested in Ruby as well. 
![pre_every_item_bug](https://user-images.githubusercontent.com/1354217/166069324-1fdfccdc-03b3-4ee2-98b0-70c83aa8a5f3.gif)

**Comment by pokey** [comment] 2022-04-30 07:01
Duplicate of #299

**Comment by pokey** [comment] 2022-04-30 07:05
Re ambiguity around correct behaviour, I don't think there's any ambiguity wrt this bug. If there are 5 items and 5 comments, there should be 5 selections, but today there are 10

The question of whether we want to include trailing comments in items themselves strikes me as a separate issue

**Closed by pokey** 2022-04-30 07:05 UTC
Labels: bug

**Comment by Will-Sommers** [comment] 2022-05-02 18:01
ty — will search issues prior to filing next.
