### ISSUE TITLE
"short paint" (boundedNonWhitespaceSequence?) is undocumented

### ISSUE THREAD

**Issue by jmegner** [cursorless-dev/cursorless#1549] opened 2023-06-22 20:32 UTC
"short paint" (boundedNonWhitespaceSequence?) is undocumented; even a very short blurb in the reference would be great

**Comment by AndreasArvidsson** [comment] 2023-07-05 10:36
Duplicate of #839

**Closed by AndreasArvidsson** 2023-07-05 10:36 UTC
