### ISSUE TITLE
cursorless-talon fails weirdly when vscode isn't installed

### ISSUE THREAD

**Issue by lunixbochs** [cursorless-dev/cursorless#1019] opened 2022-10-07 19:11 UTC
```
   12:                              lib/python3.9/threading.py:937* # loader thread
   11:                              lib/python3.9/threading.py:980* 
   10:                              lib/python3.9/threading.py:917* 
    9:                                 app/resources/loader.py:894| 
    8:                                 app/resources/loader.py:844| 
    7: -----------------------------------------------------------# [stack splice]
    6: -----------------------------------------------------------# 'ready' user.cursorless-talon.src.marks.mark:on_ready()
    5: lib/python3.9/site-packages/talon/scripting/dispatch.py:134| result = cb(*args)
    4:                 user/cursorless-talon/src/marks/mark.py:242| vscode_settings_path: Path = actions.u..
    3:  lib/python3.9/site-packages/talon/scripting/actions.py:88 | return func(*args, **kwargs)
    2:       user/cursorless-talon/src/apps/vscode_settings.py:75 | return pick_path(
    1:       user/cursorless-talon/src/apps/vscode_settings.py:69 | return max(existing_paths, key=lambda path: path.stat().st_mtime)
ValueError: max() arg is an empty sequence
```

**Comment by auscompgeek** [comment] 2022-10-08 02:28
Duplicate of #543

**Closed** 2022-10-08 02:28 UTC
