### ISSUE TITLE
Don't include surrounding lines in scope fixtures

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#2139] opened 2023-12-14 17:39 UTC
Only include lines containing the given target. That will make it easier to read tests that include multiple targets. We have line numbers, so shouldn't really lose any information. See https://github.com/cursorless-dev/cursorless/pull/2102#discussion_r1423873354 for more info

**Comment by AndreasArvidsson** [comment] 2024-02-10 06:01
Duplicate of #2164

**Closed by AndreasArvidsson** 2024-02-10 06:01 UTC
