### ISSUE TITLE
Head and tail are opposites of each other for words verses lines

### ISSUE THREAD

**Issue by fatalerrorx** [cursorless-dev/cursorless#1392] opened 2023-04-07 00:35 UTC
When you say "bring tail bat"  on a line. Head is defined as the beginning of a line and tail the end of the line.  But when you say "bring tail second word bat"  tail is the beginning of a word and head is the end of a word.  This is unintuitive I think the behavior should be the same for words and lines.

**Comment by pokey** [comment] 2023-04-07 06:02
Duplicate of #972 / #939

**Closed** 2023-04-07 06:02 UTC
